---
title: "Homework 2"
author: "Mari Sanders"
date: "2024-09-24"
output: github_document
---
```{r message=FALSE, }
library(tidyverse)
library(readxl)
```

# Problem 1 

```{r}
transit_df <- read_csv("data_hw2/nyc_subway_data.csv") %>% 
  janitor::clean_names() %>% 
  select(
    -c("division", "entrance_type", "exit_only", "staffing", "staff_hours",
       "ada_notes", "free_crossover", "north_south_street", "east_west_street", 
       "corner", "entrance_latitude", "entrance_longitude", "station_location", 
       "entrance_location")
  ) %>% 
  mutate(
    entry = case_match(
      entry, 
      "YES" ~ TRUE, 
      "NO" ~ FALSE
    )
  )
```


# Problem 2 

```{r}
mr_trash_wheel_df <- read_excel("data_hw2/202309_Trash_Wheel_Collection_Data.xlsx", 
                                range = "A2:N586", sheet = "Mr. Trash Wheel") %>% 
  janitor::clean_names() %>% 
  select(
    -c("month", "year", "date", "homes_powered")
  ) %>% 
  mutate(
    sports_balls, sports_balls = as.integer(sports_balls)) %>% 
  mutate(trash_wheel = "Mr.")


prof_trash_wheel_df <- 
  read_excel("data_hw2/202309_Trash_Wheel_Collection_Data.xlsx", 
             range = "A2:M108", sheet = "Professor Trash Wheel") %>% 
  janitor::clean_names() %>% 
  select(
    -c("month", "year", "date", "homes_powered")
  ) %>% 
  mutate(trash_wheel = "Professor")

gwynnda_df <- 
  read_excel("data_hw2/202309_Trash_Wheel_Collection_Data.xlsx", 
             range = "A2:L157", sheet = "Gwynnda Trash Wheel") %>% 
  janitor::clean_names() %>% 
  select(
    -c("month", "year", "date", "homes_powered")) %>% 
  mutate(
    trash_wheel = "Gwynnda"
  )

trash_wheel_df <- 
  bind_rows(mr_trash_wheel_df, prof_trash_wheel_df,gwynnda_df) %>% 
  relocate(trash_wheel, .after = dumpster)
```



